# Generated by Django 3.1.2 on 2020-12-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.currency'),
        ),
    ]
